DROP TABLE IF EXISTS DEPARTMENT;


CREATE TABLE DEPARTMENT
(DEPT_ID INT(9) AUTO_INCREMENT PRIMARY KEY,
DEPT_NAME VARCHAR(50),
MANAGER_ID VARCHAR(100),
LOCATION_ID INT(10),
MANAGER_NUMBER INT(10),



DROP TABLE IF EXISTS EMPLOYEE;


CREATE TABLE EMPLOYEE
(EMP_ID INT(9) AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(50),
EMAIL VARCHAR(100),
PHONE_NUMBER(10),
DEPT_ID INT(9),
FOREIGN KEY (DEPT_ID) REFERENCES DEPARMENT(DEPT_ID)
);

