package com.spring.utils;

public class QueryBuilder {
	public static final String NJ_GET_ALL = "SELECT * FROM DEPARTMENT";
	public static final String NJ_INSERT = "INSERT INTO DEPARTMENT(DEPT_NAME,MANAGER_ID,LOCATION_ID,MANAGER_NUMBER)VALUES(:K_DEPT_NAME,:K_MANAGER_ID,:K_LOCATION_ID,:K_MANAGER_NUMBER)";
	public static final String NJ_GET_DEPT_BY_ID = "SELECT *FROM DEPARTMENT LEFT JOIN EMPLOYEE ON DEPARTMENT.DEPT_ID = EMPLOYEE.DEPT_ID";
	
	public static final String NJ_GET_ALLl = "SELECT * FROM EMPLOYEE";
	public static final String NJ_INSERTT = "INSERT INTO EMPLOYEE(NAME,EMAIL,PHONE_NUMBER,DEPT_ID) VALUES(:K_NAME,:K_EMAIL,:K_PHONE_NUMBER,K_DDEPT_ID)";
	public static final String NJ_GET_EMP_BY_ID = "SELECT *FROM DEEPARTMENT RIGHT JOIN EMPLOYEE ON DEPARTMENT.DEPT_ID = EMPLOYEE.DEPT_ID";
	
}
